sudo: false
dist: trusty
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy-5.4.1"
  - "pypy-5.6.0"
  - "pypy-5.7.1"
  - "pypy2.7-5.8.0"
  - "pypy2.7-5.9.0"
  - "pypy3.5-5.8.0"
  - "pypy3.5-5.9.0"
matrix:
  include:
  - python: 3.7
    dist: xenial
    sudo: true
  - python: 3.8
    dist: xenial
    sudo: true
  - python: pypy
    dist: xenial
    sudo: true
  - python: pypy3
    dist: xenial
    sudo: true
before_install:
  - pip install --upgrade pip setuptools
install:
  - pip install -r requirements.txt
  - pip install coveralls
script: coverage run --source=eadapters setup.py test
after_success: coveralls
deploy:
  provider: pypi
  user: joamag
  password:
    secure: EB/AsLi8UOAILqeT0kJN8Inb9QcfUELOmExb0u9z+Gh1rSLf1hK0PrAHB2/8fA1fjD2rEUkSOCysg1Kl3HoGy5R1ESiDRt5iK3NUEOQi8bnno3GDzWeWyj60DzbH1NzsOIf0+ezxtLFOUC6oSVPmJreELq0gsMG7HTgvMG00phNT27yUw8p/rye9ial6InTZt379id2M7cYtuSoresaa/PjUWc1iZz5IwIc938ijN/g08xrvsItZR8Q7OOyEJxoepIpORnhGPf6cJ0Q2DeUIvsFo4ykOppmJSZbSRo+6wvIjk53lr2JC/ttv67Fds2gT79NfR84cZ7nhKGXP0hyDmYV3K4bqBdckSzTNbLpQiFUiHiXzFWoGa5Yu0trbAOZxejozDHLu2oF4LdwOjjMRDnh/1d7XU1Q5sx9ppwwiGMXVWtWJudP41kS/B731DnTYQy5eec0cfpeezeh6QXIfLGa2uZRLmkMMe/RrcP7D8LASfMEdRNwy0XdpMbPJhFPU2Z35l+IxUtwTjMS6eUg8+S2RHhikmQaiW9guDWo9oT8f9K/Nv7C+t0yX0+iRMv2lgfuHYVQTa0Jrx7hZL5XUEdO5B3kfhrzkOkYuUb+DptwhPYDEuwQMv4dBXDdHyFQWWpgx6h7Ch53dYuN0xrpJvTLrzt5DWOdXoIRfEaK32gM=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: "2.7"
