sudo: false
dist: trusty
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy-5.3.1"
  - "pypy-5.4.1"
  - "pypy-5.6.0"
  - "pypy-5.7.1"
  - "pypy3-2.4.0"
  - "pypy2.7-5.8.0"
  - "pypy3.5-5.8.0"
before_install:
  - if [[ $TRAVIS_PYTHON_VERSION != "3.2" ]] && [[ $TRAVIS_PYTHON_VERSION != "3.3" ]] && [[ $TRAVIS_PYTHON_VERSION != "pypy3-2.4.0" ]]; then pip install --upgrade pip setuptools; fi
  - if [[ $TRAVIS_PYTHON_VERSION == "3.2" ]]; then pip install --upgrade "pip<8.0" "setuptools<20.0"; fi
  - if [[ $TRAVIS_PYTHON_VERSION == "3.3" ]] || [[ $TRAVIS_PYTHON_VERSION == "pypy3-2.4.0" ]]; then pip install --upgrade "pip<10.0" "setuptools<24.0"; fi
install:
  - pip install "pkginfo<1.3"
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install twine
script: if [[ $TRAVIS_PYTHON_VERSION != "3.2" ]]; then coverage run --source=eadapters setup.py test; else python setup.py test; fi
after_success: if [[ $TRAVIS_PYTHON_VERSION != "3.2" ]]; then coveralls; fi
deploy:
  provider: pypi
  user: joamag
  password:
    secure: EB/AsLi8UOAILqeT0kJN8Inb9QcfUELOmExb0u9z+Gh1rSLf1hK0PrAHB2/8fA1fjD2rEUkSOCysg1Kl3HoGy5R1ESiDRt5iK3NUEOQi8bnno3GDzWeWyj60DzbH1NzsOIf0+ezxtLFOUC6oSVPmJreELq0gsMG7HTgvMG00phNT27yUw8p/rye9ial6InTZt379id2M7cYtuSoresaa/PjUWc1iZz5IwIc938ijN/g08xrvsItZR8Q7OOyEJxoepIpORnhGPf6cJ0Q2DeUIvsFo4ykOppmJSZbSRo+6wvIjk53lr2JC/ttv67Fds2gT79NfR84cZ7nhKGXP0hyDmYV3K4bqBdckSzTNbLpQiFUiHiXzFWoGa5Yu0trbAOZxejozDHLu2oF4LdwOjjMRDnh/1d7XU1Q5sx9ppwwiGMXVWtWJudP41kS/B731DnTYQy5eec0cfpeezeh6QXIfLGa2uZRLmkMMe/RrcP7D8LASfMEdRNwy0XdpMbPJhFPU2Z35l+IxUtwTjMS6eUg8+S2RHhikmQaiW9guDWo9oT8f9K/Nv7C+t0yX0+iRMv2lgfuHYVQTa0Jrx7hZL5XUEdO5B3kfhrzkOkYuUb+DptwhPYDEuwQMv4dBXDdHyFQWWpgx6h7Ch53dYuN0xrpJvTLrzt5DWOdXoIRfEaK32gM=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: "2.7"
